### ISSUE TITLE
When will the demo and checkpoint be available?

### ISSUE THREAD

**Issue by Rane2021** [showlab/videollm-online#1]
Great work!

**Comment by chenjoya** [comment]
Thank you!

We have released Gradio demo 

<img width="1361" alt="image" src="https://github.com/showlab/videollm-online/assets/20626415/19bf9639-06cf-4b39-b314-8213b4ce6e8b">

You can visit https://huggingface.co/spaces/chenjoya/videollm-online to try.

**Comment by Rane2021** [comment]
Thanx! Very nice!
