### ISSUE TITLE
Dataset Downloading and Usage

### ISSUE THREAD

**Issue by YiwuZhong** [showlab/videollm-online#10]
Thanks for sharing this nice work!

I was wondering if the full Ego4D-v2 dataset was used for training, or just a subset. It's not clearly demonstrated in the paper or this repo. It would be great if the authors could provide some guidelines for data downloading and usage (such as the folder structure, and which folder should your provided streaming dialogue JSON data be put to).

Best regards,
Yiwu

**Comment by chenjoya** [comment]
Hi Yiwu, thanks for your interests! For data, we aggregate all Ego4D-v2 downstream benchmark training/validation sets. You only need to make the dataset annotation path as ```datasets/ego4d/v2/annotations```, then the program will do that.

These are benchmarks (Ego4D v2.1, with goalstep) we used:

<img width="662" alt="image" src="https://github.com/showlab/videollm-online/assets/20626415/5c137a43-5853-4da9-b0a9-cfef018af051">

Implementation details from:

https://github.com/showlab/videollm-online/blob/df8982632086b39fcc492db90c54bd68ae24ba5a/data/ego4d/narration.py#L16




(BTW, before this work I learned your ProcedureVRL. Thank you!)

**Comment by YiwuZhong** [comment]
@chenjoya Hi Joya, thanks for your previous reply!

A few more questions about the dataset: 

1. According to README in the preprocess folder, only the videos in `datasets/ego4d/v2/full_scale` were preprocessed. 
2. How about the video clips in `clips` folder of Ego4D dataset? 
3. Did you only use the videos in `ego4d/v2/full_scale`? Besides, did you use the ["grouped videos" mentioned in the goal-step release](https://ego4d-data.org/docs/updates/#v21-update)?

**Comment by chenjoya** [comment]
Hi Yiwu,

Thank you. 

1. I thought ```clips``` contains the benchmark video clips of ```full_scale```, thus I only use videos in ```full_scale```. Using ```full_scale``` can also get a small clip of the video. For example, the narration video clips are ~5 minutes, so I will crop the embedding by its start and end time:

https://github.com/showlab/videollm-online/blob/b1530e9f74f2ce2b5656684cd360f922610dccc4/data/ego4d/narration.py#L102

https://github.com/showlab/videollm-online/blob/b1530e9f74f2ce2b5656684cd360f922610dccc4/data/stream.py#L91

2. I am sorry that I dont know the details of ```grouped videos```. Previously ```v2/full_scale/``` has 9600+ videos. Then I update goalstep videos to ```v2/full_scale```. It has 9818 videos now. Does that mean I used "grouped videos"?

Feel free to contact me for any problem!

**Comment by YiwuZhong** [comment]
Thanks for your helpful information!

For item 2, I conjecture that the "grouped videos" could be duplicated to some of the videos in full scale. But it might not be a big problem.

Also, did you use the same code to process COIN videos? Such as downsampling and feature extraction. Thanks!

**Comment by chenjoya** [comment]
Thank you. Yes, the same. But the company does not allow YouTube videos, so COIN is only for separate downstream tasks.

**Comment by YiwuZhong** [comment]
@chenjoya Do you mind sharing the versions of key packages you used? Such as torch, cuda, transformers, deepspeed, flash-attn, etc. I encountered errors with DeepSpeed and not sure whether it is version conflict. Thanks!

**Comment by chenjoya** [comment]
No problem 

```
torch==2.3.1
transformers==4.42.4
deepspeed==0.14.4
flash-attn==2.6.1
peft==0.11.1

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
```

Could you also share the errors you encountered? Since I always use the latest env. Thank you so much!

**Comment by YiwuZhong** [comment]
I just made sure each of these versions matches yours. But the same warnings came out when `import deepspeed`:
 
```
 [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-devel package with yum
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.1), only 1.0.0 is known to be compatible
```
and an error:

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/projects/video/videollm-online/train.py", line 40, in <module>
[rank0]:     train()
[rank0]:   File "/projects/video/videollm-online/train.py", line 8, in train
[rank0]:     args = parse_args()
[rank0]:   File "/projects/video/videollm-online/models/__init__.py", line 8, in parse_args
[rank0]:     args, = HfArgumentParser(LiveTrainingArguments).parse_args_into_dataclasses()
[rank0]:   File "/anaconda3/envs/videollm/lib/python3.10/site-packages/transformers/hf_argparser.py", line 348, in parse_args_into_dataclasses
[rank0]:     raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
[rank0]: ValueError: Some specified arguments are not used by the HfArgumentParser: ['\r']
```

**Comment by chenjoya** [comment]
Sorry. Let me have a try. Which scripts do you run?

**Comment by YiwuZhong** [comment]
I used `scripts/ego4d/live1+.sh` which I thought was the script for your main model training.

**Comment by chenjoya** [comment]
Yes it is. I cloned this repo and have a try. In my side I cannot see this problem:

<img width="920" alt="image" src="https://github.com/user-attachments/assets/2668c901-8b46-4f68-b74c-c5f846a5ceee">

Now the model is preparing to load, which means the arg parsing has been succeed. 

It seems to be a arg parsing problem. I guess there might be some unexpected chars in your ```scripts/ego4d/live1+.sh```... Could you try to copy that again?

**Comment by chenjoya** [comment]
(You can ignore the warning. It does not matter)

**Comment by YiwuZhong** [comment]
Now the issue is resolved, by re-copying linux format of bash file. I thought it was the warning message that some packages were not installed correctly. Thank you for your help!

**Comment by chenjoya** [comment]
Nice! My great pleasure!

**Comment by YiwuZhong** [comment]
Hi @chenjoya, thanks for your previous helpful information.

I was wondering how to evaluate the pre-trained model as Table 1 of the paper. Do I only need to specify the evaluation dataset and use evaluate.py? Besides, after pre-training, there seems to no model checkpoints saved. Did I need to specify which parameters to save via `finetune_modules`?

**Comment by chenjoya** [comment]
Hi Yiwu, so sorry for the delayed response. Yes, the only thing to do is specify them via finetune_modules. PEFT will only save them and the LoRA weights.

Could you give me a list of your env? I will try to debug that.

**Comment by YiwuZhong** [comment]
My environment is the same as the one you provided:

`torch==2.3.1
transformers==4.42.4
deepspeed==0.14.4
flash-attn==2.6.1
peft==0.11.1
`

To double-check, I used the following script:

```
deepspeed evaluate.py \
    --live_version live1+ \
    --train_datasets ego4d_narration_stream_train \
    --eval_datasets ego4d_narration_stream_val \
    --num_train_epochs 2 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --gradient_checkpointing True \
    --eval_strategy no \
    --prediction_loss_only False \
    --save_strategy epoch \
    --learning_rate 0.0002 \
    --optim adamw_torch \
    --lr_scheduler_type cosine \
    --warmup_ratio 0.05 \
    --logging_steps 1 \
    --dataloader_num_workers 16 \
    --bf16 True \
    --tf32 True \
    --report_to tensorboard \
    --resume_from_checkpoint outputs/ego4d_narration+goalstep_livechat+robustness/live1+ \
```

**Comment by YiwuZhong** [comment]
Update: The above script works for the COIN benchmark, referring to your `coin/live1+_evaluate.sh`. But somehow it doesn't work for narration evaluation.

**Comment by chenjoya** [comment]
Hi Yiwu, currently I am working in a new cluster. I finished all data preparing and now start to train COIN. Please wait several hours and I will get back to you!

<img width="909" alt="image" src="https://github.com/user-attachments/assets/315319d2-0fcd-4966-927e-07d5ea1736a2">

**Comment by chenjoya** [comment]
Hi Yiwu, the bug in COIN evaluation has been fixed. I reproduced from scratch in a new cluster.

The main reason should be the unstable training. My current env is torch 2.4.0, cuda 12.4, transformers 4.44.0. When I try to use lr = 2e-4, it cannot converge, which I also meet in other scenarios (but previously it can converge...). I try to decrease the lr / 2 = 1e-4, still 5 epoch, then get the results

<img width="1297" alt="image" src="https://github.com/user-attachments/assets/02a9c719-e455-4f0b-b8e5-8a867df5f67e">

Lower than the paper due to lr / 2. Will update once I get a good epoch and lr parameters.

Meanwhile, I made some updates on the COIN dataset and removed some useless codes. Recommend to pull them.

**Comment by YiwuZhong** [comment]
Thanks for your update! @chenjoya 

What is the rough value of loss after converging? Besides, it seems that the evaluation of narration and LTA has some errors (see the comments above). Could you please also take a look at them? Thanks!

**Comment by chenjoya** [comment]
Hi Yiwu, sorry that I recently busy with other projects, do not have many GPUs to re-implement. In my experience, the key to get high accuracy on COIN is (1) avoid training loss spike. This is very important, please check the log. If that happens, you can stop and try the next config 😂 (2) Try lr as high as possible but ensure loss spike is not appeared.

Yesterday I tried some simple parameters, lr = 0.00015, stream_loss_weight=0.5, and I have got the similar results to the paper: 

<img width="1248" alt="image" src="https://github.com/user-attachments/assets/e0688a77-79b7-46e5-8206-3112985747bd">

‘eval_coin_step_test_accuracy’: 62.7394328517924
’eval_coin_next_test_accuracy’: 48.5977275995973
‘eval_coin_task_test_accuracy’: 92.22408026755853
‘eval_coin_procedure_test_accuracy’: 48.84329225761451
‘eval_coin_taskprocedure_test_accuracy’: 53.641383318802674

Training with longer epochs should the match the paper. But now GPUs are not free again. Will update once it has been done. Also will fix LTA in 2 days. Many thanks for your patience!
