### ISSUE TITLE
Meaning of Llama-3 Upgraded Version

### ISSUE THREAD

**Issue by Lvvv11** [showlab/videollm-online#11]
First of All, Thank you for the great work!!

I've been reading your recent paper and I found it very insightful! However, I have a question regarding a note on the first page. It says, "This is the Llama-3 upgraded version for CVPR camera-ready."

Could you please clarify the meaning of this sentence? Specifically, does this mean that this repository contains an upgraded version of Llama-3? I'm having some trouble understanding the exact implication.

Thank you for your help!

**Comment by chenjoya** [comment]
Thanks for your interests! When we submit CVPR, Llama-3 was not released and we built model upon Llama-2. After camera ready, Llama-3 was released thus we replace the previous Llama-2 with to Llama-3 and retrain the model.

**Comment by Lvvv11** [comment]
Thank you for your kind answer :) Have a nice day!

**Comment by chenjoya** [comment]
Thank you!
