### ISSUE TITLE
How large is the dataset？

### ISSUE THREAD

**Issue by wenyuqing** [showlab/videollm-online#14]
Hi, thanks for your great work. Could you tell me how large is the dataset, and how much storage space is needed to prepare for it?

**Comment by chenjoya** [comment]
Hi yuqing,  many thanks for your interests! The original Ego4D videos are 7.1T, after our encoding (SigLIP, 2FPS, 384x384, 1+3x3 token per frame), that is ~1.1T. I am sorry that I cannot find such a large space to release that, but the visual preprocessing scripts are released: https://github.com/showlab/videollm-online/tree/main/data/preprocess

**Comment by wenyuqing** [comment]
Thanks for your quick reply! Do you have small subsets so that I can quickly run the training and inference code on it without downloading the whole large data? If so, it will be very helpful, thanks!

**Comment by chenjoya** [comment]
Ok. My recommendation is to download a subset (e.g. Goalstep benchmark) of Ego4D, then filtering video ids to run the code, specifically, 

1. Review and accept Ego4D the terms of our license agreement at https://ego4d-data.org/docs/start-here/#license-agreement, to get the aws key;

2. Download Ego4D LTA benchmark data. We only download 448x448 videos. That would be faster:

```
pip install ego4d
pip install awscli
aws configure # set the obtained aws key
ego4d --output_directory="./gg" --datasets full_scale --benchmarks goalstep annotations 
```

Only 800+ videos in goalstep, ~400G, so the download should be faster.

3. Now suppose you have downloaded all videos in goalstep. You can filter the annotations of https://huggingface.co/datasets/chenjoya/videollm-online-chat-ego4d-134k by your downloaded video uids. Then it should be work to use the scripts to train the model!

4. If you just need to test the demo, no need to download the dataset, just change the video path in demo scripts. Please refer to 

```
python -m demo.app --resume_from_checkpoint chenjoya/videollm-online-8b-v1plus
```

or 

```
python -m demo.cli --resume_from_checkpoint chenjoya/videollm-online-8b-v1plus
```

**Comment by wenyuqing** [comment]
Thanks for your quick and warm reply! It's very helpful, I'll try it ASAP.

**Comment by wenyuqing** [comment]
So after downloading the goalstep subset(step 2 in your instruction), should I preprocess the videos by this scripts?  [https://github.com/showlab/videollm-online/tree/main/data/preprocess](url)  . In my understanding this script is to sample the videos with 2 fps, and resize to 384 spatial resolution, is that right?  Do I need to do the "Narration Refinement" by my self or just use the refined version from you url [https://huggingface.co/datasets/chenjoya/videollm-online-chat-ego4d-134k](url)?

**Comment by chenjoya** [comment]
Hello, thanks for your efforts. Yes you need to preprocess videos and encode. But you don't need to refine narration again. Thats been done.

**Comment by chenjoya** [comment]
Close this issue. Feel free to reopen it.
