### ISSUE TITLE
Error with the demo

### ISSUE THREAD

**Issue by wenyuqing** [showlab/videollm-online#15]
Hi, I run the demo with app.py but get this error:
<img width="1139" alt="image" src="https://github.com/user-attachments/assets/d138b8c1-f116-4348-8d90-e37d6a126d59">
Could you please help me with that?

I change the backend from "video_reader" to "pyav" because it sames that my pytorch doesn't support "video_reader", and the other code are unchanged.
`# torchvision.set_video_backend('video_reader')
torchvision.set_video_backend('pyav')`

**Comment by wenyuqing** [comment]
I forgot to install av, and this error disappears after installing av, but the program seems to be stuck at here.
<img width="1165" alt="image" src="https://github.com/user-attachments/assets/ffaecf2b-783d-4ce4-849c-2c7a78c220fe">
The output in ther terminal is like this:
<img width="714" alt="image" src="https://github.com/user-attachments/assets/046dcd2f-3624-4a72-bfd6-90ea6ae00aa8">

**Comment by chenjoya** [comment]
It is weird. Could you try cli.py? Also what is your GPU

**Comment by wenyuqing** [comment]
I use A100, cli.py seems to work, it ouputs like this and end here:
<img width="704" alt="image" src="https://github.com/user-attachments/assets/53c8da53-1d00-49a0-8e4d-b099bcd6aeb0">

**Comment by chenjoya** [comment]
Ok but the sentence seems not ending... Have you changed eos token id?

**Comment by wenyuqing** [comment]
No, in fact I think I haven't done any changes to the code except for the video reader backend, you mean the output of the cli.py is not correct, either?

**Comment by chenjoya** [comment]
Yes, let me try that. Please wait a moment

**Comment by chenjoya** [comment]
Hi, my side is correct:

<img width="829" alt="image" src="https://github.com/user-attachments/assets/6323094d-c301-4e31-b439-ab8610186252">

The possible reason is the HF Llama-3 version. HF originally has the wrong EOS token <|end_of_text|> (128001), but the actual eos token in chatting should be <|eot_id|> (128009). Could you check your llama-3 HF cache?

<img width="312" alt="image" src="https://github.com/user-attachments/assets/16a2fa13-c2a6-45e3-a6f1-a86a6f32a33d">

By default, the path is: ~/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3-8B-Instruct/snapshots/xxx(see what folders you have under snapshots)/config.json. Make sure eos_token_id is 128009.

**Comment by chenjoya** [comment]
Hi wenyu, does the above solve your problems ;)

**Comment by wenyuqing** [comment]
I'm very sorry for the late reply because I caught a cold recently and It also took me a while to download the newer llama-3 version. The new version seems to be correct, the config is as follows. But the result still seems to be wrong:
<img width="408" alt="image" src="https://github.com/user-attachments/assets/b84796a6-3e77-4443-adc3-087b1bb1520e">
<img width="1342" alt="image" src="https://github.com/user-attachments/assets/071ebda6-f6fd-4244-8af7-889667246742">

**Comment by wenyuqing** [comment]
oh, I find the problem, the newer version llama3 I download is from a third-party url, and the eos token is not changed in the version I downloaded:
<img width="1131" alt="image" src="https://github.com/user-attachments/assets/5d7a8360-1b53-43ed-8230-0769253f5b7a">
I renew it and It works fine!:
<img width="1349" alt="image" src="https://github.com/user-attachments/assets/b33a6a7a-2a8b-4183-844a-f0444480ffd0">

Thanks again for your warm help and great work.

**Comment by chenjoya** [comment]
Nice!

**Comment by alpacaduby** [comment]
> oh, I find the problem, the newer version llama3 I download is from a third-party url, and the eos token is not changed in the version I downloaded: <img alt="image" width="1131" src="https://private-user-images.githubusercontent.com/48059861/351561707-5d7a8360-1b53-43ed-8230-0769253f5b7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTUwMTcsIm5iZiI6MTcyMzgxNDcxNywicGF0aCI6Ii80ODA1OTg2MS8zNTE1NjE3MDctNWQ3YTgzNjAtMWI1My00M2VkLTgyMzAtMDc2OTI1M2Y1YjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDEzMjUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1OGQzZDEwYjdjNDQ0ZGFkODFjMzUxNDdkYTU0MmM3NjNiYjc5ZmE1ZDRkZDM0NDE1YWQ1NzRkMGUxYjFmNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p0LXpJrEr2cRTllirL-auAZiRRm1453TTCp505-M_uA"> I renew it and It works fine!: <img alt="image" width="1349" src="https://private-user-images.githubusercontent.com/48059861/351561766-b33a6a7a-2a8b-4183-844a-f0444480ffd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTUwMTcsIm5iZiI6MTcyMzgxNDcxNywicGF0aCI6Ii80ODA1OTg2MS8zNTE1NjE3NjYtYjMzYTZhN2EtMmE4Yi00MTgzLTg0NGEtZjA0NDQ0ODBmZmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDEzMjUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YWFhNzczY2UxMDZlYThhYzE4MWUzNDYwZDJjMzY5ZmI1MjVlNjJmYWQyM2ZjMGM0MzE2NDI4NWZmZDM3MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7IJcoP1HirjKhuiopW6gRfg-tCeBpanuDc6v7aJVbKc">
> 
> Thanks again for your warm help and great work.

Hello, I also meet this problem. I also download llama3 from third-party url. However, the output did not change even if I changed config.json(128009) and tokenizer_config.json as you said, is there anything else needed to change? Thanks a lot.
