### ISSUE TITLE
error in demo/cli.py

### ISSUE THREAD

**Issue by alpacaduby** [showlab/videollm-online#17]
Thanks for the great work.

When I run `demo/cli.py` following 
```
python -m demo.cli --resume_from_checkpoint chenjoya/videollm-online-8b-v1plus
```
I encounter this error if I replace `src_video_path = 'demo/assets/cooking.mp4'` with `src_video_path = 'demo/assets/bicycle.mp4'`:
```
tensor([[13]], device='cuda:0') != 933
```
in `videollm-online-main/demo/inference.py`, line 44
How can I solve this problem?

Also I find the model keeps repeating 'You hold a piece of wood.' when I use cooking.mp4 as the input without changing the original  question, what can be the reason of this phenomenon? 

Thanks for your answer.

**Comment by chenjoya** [comment]
Hello, seems to be the same question as #15. Could you update your transformers version & the llama3 cache?

**Comment by chenjoya** [comment]
Closed. Feel free to reopen the issue if you do not solve that.
