### ISSUE TITLE
Why the data preprocess command will end quickly?

### ISSUE THREAD

**Issue by wenyuqing** [showlab/videollm-online#19]
Hi, I've downloaded about 600 videos, and I run the command:
`python -m data.preprocess.ffmpeg --num_gpus 8 --frame_fps 2 --frame_resolution 384 --video_dir datasets/ego4d/v2/full_scale`
,but this will end quickly without any output informations and the number of videos it processed is only 35.
Have you met this problem before? If so, what should I do for that?
Thanks!

**Comment by chenjoya** [comment]
Hi wenyu, this script runs a slurm task, it will run in your background rather than occupy your terminal. You may observe the process via the log under outputs/preprocess/

**Comment by wenyuqing** [comment]
It seems that the process exited:
<img width="939" alt="image" src="https://github.com/user-attachments/assets/20cd4054-8516-4df6-bf26-39d6f4586f8f">

**Comment by chenjoya** [comment]
Hi, it seems that you are running on a single node, so the timeout_min is used, but it is too short for long video processing. I just updated https://github.com/showlab/videollm-online/blob/main/data/preprocess/ffmpeg.py. Could you try again?

**Comment by wenyuqing** [comment]
It seems to work now! Thank you very much for your help!

**Comment by chenjoya** [comment]
Nice!

**Comment by wenyuqing** [comment]
So for encode preprocess, should I also change the code to single node?

**Comment by chenjoya** [comment]
Yes should do. I have modified them.

**Comment by wenyuqing** [comment]
Thanks a lot!
