### ISSUE TITLE
Strange output for demo/assets/cooking.mp4

### ISSUE THREAD

**Issue by Kiki2049** [showlab/videollm-online#21]
Thanks for the great work.

I ran `cli.py` and only changed `for i in range(100): ` to `for i in range(215):` and the model produced output for every frame, which doesn't seem to satisfy your original intent of designing the model to **KEEP SILENCE**, and it resulted in a steady drop in FPS.

Is this normal and how should I fix this issue?
<img width="1451" alt="image" src="https://github.com/user-attachments/assets/c0ad96b7-dd08-4bae-9384-90e88e00e5f2">

Also, the MOTIVATION of the article is to make an **ALWAYS-ON ONLINE ASSISTANT**, which means that the model will continue to receive video streams for even more than just ten minutes. As an autoregressive model, its output seems to slow down with increasing context? (It seems that every output and video frame of the model is used as a context for subsequent generation). 

Have you devised any strategy to solve this problem? (The architecture uses Continuous Key-Value Cache, but its growing size may also be a new problem?)

Thank you again for your great work and I look forward to hearing from you!

**Comment by chenjoya** [comment]
Many thanks for your interests! Yes I observed that when the video is too long, there will be some weird behaviors. A possible reason is, Llama-3.0 only has 8K context window. When the video is too long, the input sequence will be out of the window, then causing some weird behaviors. We will try Llama-3.1, which has a 128K context window. 

Data should also be a problem. We dont have many high-quality long streaming data. So for the less trained range (e.g. > 5min), the model performance will be decreased. 

Speed/GPU memory of long sequence is a problem for our academic community, but it may not be a problem again for the most advanced industry. If you try to give GPT-4o a very long prompt, its output speed is still very fast. I guess the current sys developments have been enough for real-time hour-long video inference (~10k frames, ~100k vision tokens).

**Comment by chenjoya** [comment]
Close the issue. Feel free to reopen this if you have further questions.

**Comment by yankee624** [comment]
@chenjoya The max_num_frames is set to 1200 when training Live1+ model, as shown below.
https://github.com/showlab/videollm-online/blob/755e2652a651ae2e43bb2f9d28281a2540a3bbac/models/arguments_live.py#L47

Since one frame = 10 tokens, this will lead to maximum 12000 visual tokens + additional language tokens. This exceeds the 8K context length of Llama-3.0. Is it ok to train with these large number of tokens?
(I think one possible solution may be to split the video into chunks, where each chunk consists of several turns. Splitting would not be a big problem if the turns that are far away from each other are somewhat independent to each other.)

**Comment by chenjoya** [comment]
The correct way should still be using the long-context model, e.g. 128K Llama3.1. It increases the RoPE base frequency and trains on long-context language data, a standard way. Simply train Llama3 in HF can accept tokens > 8K, but it uses the ROPE interpolation, may cause some problems.

“Split the video into chunks” is a feasible solution for current data. I also recommend the sliding window, which may protext context better.

**Comment by yankee624** [comment]
Thank you for the reply!
Actually RoPE scaling is disabled by default in [Llama3-8b-instruct config](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/config.json). So the scaling isn't used in videollm-online model (unless we specify to turn on the scaling), and it becomes problem when tokens > 8K.

**Comment by chenjoya** [comment]
Get it, thanks for checking. Scaling RoPE usually needs the model to be trained with the new theta, and interpolation does not require that but usually perform not so well. So I mean Llama-3 RoPE interpolation (implemented in HF) may not be enough for our long-context sequence.
