### ISSUE TITLE
Cost of the GPU memory

### ISSUE THREAD

**Issue by memoiry** [showlab/videollm-online#22]
Hi dear author,

Thank you for the excellent work. I have recently been trying to reproduce your work on a machine with 8x A100 (40GB) GPUs. However, I found that training directly caused an out-of-memory issue. So, I switched from ZeRO-2 to ZeRO-3, and I found that this works. I would like to ask if there are any issues with switching to ZeRO-3? Or do you recommend training on A100s with 80GB of memory? Thank you.

Best

**Comment by chenjoya** [comment]
Hi, many thanks for your interests! The only problem of ZeRO-3 is slow. If you can accept that, then its okay. Another option is to reduce the max time of the video, which can be set in the training arguments.

**Comment by memoiry** [comment]
Got it, thanks. Additionally, if the training has converged, what is approximately the model’s loss value?

**Comment by chenjoya** [comment]
My log shows ~0.3 on Ego4D narration + goalstep livechat. But it depends on the dataset you used ;)

**Comment by memoiry** [comment]
Thanks!, I tried setting max_num_frames from 1200 to 600, and I found that the training time indeed sped up by half, but the memory usage did not significantly decrease. Do you know why?

**Comment by chenjoya** [comment]
How do you measure the memory usage? If only nvidia-smi, it may not be so accurate. Also if you set max_num_frames from 1200 to 600, video frame indices >= 600 will be dropped. Does it matter for your case?

**Comment by memoiry** [comment]
Yeah, only nvidia-smi so that I could use a smaller memory GPU.

**Comment by chenjoya** [comment]
Or you can determine the maximun sequence length your GPU supported. Try to add the padding arguments here: 

https://github.com/showlab/videollm-online/blob/b9ab59b56515092eb1de74606ab6ade0966d7fe3/data/data_collator.py#L9

e.g. try ```padding='max_length', max_length=8000```, or ```padding='max_length', max_length=10000```, observing which sequence will make your GPU OOM. According to that, determining the video length.

**Comment by chenjoya** [comment]
Close this issue. Feel free to reopen it if you have further questions.
