### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by kffeng** [showlab/videollm-online#33]
Thank you for your work, because the dataset is so big, I would like to make my own small dataset to run through your code to run videollm-online/scripts/ego4d/live1+.sh.
I'm only using one dataset ego4d_goalstep_livechat_trainval
I am wondering what is under this directory? Is it the processed .pt files and .json files? Or is it something else

**Comment by chenjoya** [comment]
Hi kffeng, sorry for the delayed response. 

So you can just 

1. download the Ego4D goalstep videos
2. get the video ids of Ego4D goalstep videos
3. select the conversations under the video id in https://huggingface.co/datasets/chenjoya/videollm-online-chat-ego4d-134k/blob/main/goalstep_livechat_trainval_filtered_21k.json
4. follow the frame preprocessing & encoding for Ego4D goalstep videos
5. now you should have .pt files and .json files. It is okay that you can start to train.

As Ego4D goalstep videos are just a few videos, I estimated that you can finish the above in one day. 

Please feel free to email me joyachen@u.nus.edu if you encounter some problems and I did not reply in Github. Many thanks for your patience!
