### ISSUE TITLE
Load in 4 bit?

### ISSUE THREAD

**Issue by johnwick123f** [showlab/videollm-online#4]
Is there a way to load this in 4 bit? That would help a lot for users with low vram! Btw, great project!

**Comment by chenjoya** [comment]
Thank you for the attention! I will take a look at bitsandbytes recently. Will update on Wednesday.

**Comment by chenjoya** [comment]
Sorry, there are some bugs when I use bitandbytes quantization_config:
```
ValueError: weight is on the meta device, we need a `value` to put in on 0.
```

which may be due to the extra connector layer:
```
self.connector = torch.nn.Sequential(
    torch.nn.Linear(config.vision_hidden_size, config.hidden_size, bias=True),
    GELUActivation(config.hidden_size),
    torch.nn.Linear(config.hidden_size, config.hidden_size, bias=True),
)
```
The nn.Sequential will make it cannot retrieve the weight (I guess?)... I still recommend you to use GPU with higher memory...

**Comment by johnwick123f** [comment]
@chenjoya oh ok, thanks anyway. I'll try it to use it with a higher memory gpu!
