### ISSUE TITLE
Demo on HuggingFace is down

### ISSUE THREAD

**Issue by hbx233** [showlab/videollm-online#5]
Hi, great work! But seems like the demo on HF is down?

**Comment by chenjoya** [comment]
Yes, HF Space is much slower than local thus I just keep a CPU run there. Please try to launch it in your local GPU, and you can also try the gradio demo:

![image](https://github.com/showlab/videollm-online/assets/20626415/c3ca399d-fa1c-4be0-9f71-fc1209f36013)

**Comment by chenjoya** [comment]
Close this issue. Feel free to reopen it if you have any problems.
